config.js, src/components/Menu/MenuItems.js, src/components/header/Header.js
Blog - main logo to redirect to masterborn.com
=> MBW-7 Blog - main logo to redirect to masterborn.com

src/components/SocialBox.js
https://masterborn.atlassian.net/browse/MBW-36
=> MBW-36 - fix sidebar margin

config.js, gatsby-config.js, package-lock.json, package.json
https://masterborn.atlassian.net/browse/MBW-33
=> MBW-33 Add Facebook pixel to blog

src/components/BackToTop.js, src/components/blog/Post.js
https://masterborn.atlassian.net/browse/MW-47
=> MW-47 Blog: Scroll up and Back buttons

package-lock.json, package.json, src/components/HoveredImageLink.js, src/components/ReadMoreLink.js, src/components/blog/BlogPostsContent.js, src/components/blog/FeaturePost.js, src/components/blog/PostShort.js, src/components/blog/PostsTiles.js, src/components/mdxComponents/CtaArticleComponent.js, src/pages/index.js, src/theme/lightTheme.js
https://masterborn.atlassian.net/browse/MW-28
=> MW-28 homepage list of articles

config.js, gatsby-browser.js, src/components/BackToTop.js, src/components/BlogListItem.js, src/components/Footer.js, src/components/Menu/ContactButton.js, src/components/Menu/MenuItems.js, src/components/Menu/MobileMenu.js, src/components/SidebarCta.js, src/components/blog/BlogContent.js, src/components/blog/Post.js, src/components/blog/RelatedArticles.js, src/components/header/Header.js, src/components/header/HeaderContainer.js, src/components/mdxComponents/CtaArticleComponent.js, src/contexts/CountryContext.js, src/layouts/PageLayout.js, src/templates/index.js, src/theme/lightTheme.js, src/utils/navigateToWebsite.js
https://masterborn.atlassian.net/browse/MW-73
=> MW-73 Article page - mobile

src/components/BlogListItem.js, src/components/Footer.js, src/components/Image.js, src/components/Menu/MenuItems.js, src/components/SidebarCta.js, src/components/blog/BlogPostsContent.js, src/components/blog/Post.js, src/components/mdxComponents/CtaArticleComponent.js
- Publish date on article page is displayed in US date format
- Remove shadow on inline article images
- CTA in the middle of article opens contact modal after click on US version
- Change text of CTA US version according to design
- CTA opens contact form after click on US version
=> MW-77 MW-78 MW-80 MW-81

package-lock.json, package.json, src/components/blog/FeaturePost.js, src/components/blog/PostShort.js
https://masterborn.atlassian.net/browse/MW-75
=> MW-75 description limit

src/components/HoveredImageLink.js, src/components/blog/FeaturePost.js, src/contexts/CountryContext.js, src/theme/lightTheme.js
https://masterborn.atlassian.net/browse/MW-76
=> MW-76 hover featured article

src/components/Footer.js
https://masterborn.atlassian.net/browse/MW-85
=> MW-85 footer-usa-text-change

gatsby-node.js, src/components/AnimateOnScroll.js, src/components/BackToTop.js, src/components/ContactModal.js, src/components/EditOnGithubLink.js, src/components/Footer.js, src/components/Menu/ContactButton.js, src/components/Menu/MenuItems.js, src/components/SidebarCta.js, src/components/blog/PostsTiles.js, src/components/mdxComponents/Anchor.js, src/components/mdxComponents/CtaArticleComponent.js, src/components/mdxComponents/index.js, src/hooks/useAlgoliaSearch.js, src/hooks/useModal.js, src/layouts/PageLayout.js, src/pages/index.js
- contact modal - added flag `alwaysHideOnSubmit` to omit the error
- commented out the code that can be useful in the future
- some minor changes
=> MW-91 lint errors

src/hooks/useModal.js
reverted change in useModal, added TODO to fix this issue later
=> stage build fix

src/validators/dealFormValidator.js, src/validators/validate.js
https://masterborn.atlassian.net/browse/MW-95
=> MW-95 blog contact form fix

gatsby-browser.js
https://masterborn.atlassian.net/browse/MW-101
=> MW-101 blog-headings-number

src/components/Footer.js, src/components/Menu/MenuItems.js, src/hooks/useActiveMenuStyles.js
https://masterborn.atlassian.net/browse/MW-105
=> MW-105 add highlight for active link in footer

src/components/Footer.js
https://masterborn.atlassian.net/browse/MW-107
=> MW-107 add mailto link

.github/workflows/CD-master.yml, .github/workflows/CD-stage.yml
https://masterborn.atlassian.net/browse/MW-113
=> [MW-113] change root urls protocol to https

src/components/Footer.js, src/components/Menu/MenuItems.js, src/components/SidebarCta.js, src/components/blog/BlogPostsContent.js, src/components/mdxComponents/CtaArticleComponent.js, src/components/mdxComponents/index.js, src/utils/navigateToWebsiteCarrier.js, src/utils/utmCampaignNames.js
https://masterborn.atlassian.net/browse/MW-102
=> [MW-102] add utm code to cta links

.gitignore, src/utils/navigateToWebsiteCareer.js
https://stackoverflow.com/questions/66015960/gatsby-navigation-with-query-parameters-do-hard-refresh-and-lose-the-parameters
⛔️ this pr could break redirect from blog to main page
=> fix: utm redirect fix

src/utils/navigateToWebsiteCareer.js
desperate problems require desperate solutions. Used browser api to guarantee redirect
=> fix: utm redirect one more time

src/components/Footer.js
Added newest office to the footer and changed width of elements to auto, so that addresses don't split.
=> MW-137 Add new office to footer

src/components/blog/BlogPostsContent.js, src/pages/index.js
Reverts masterborn/masterborn-blog#176
=> Revert "[MW-149] browser navigation fix"

gatsby-config.js, package-lock.json, package.json, src/components/Menu/MenuItems.js, src/components/blog/RelatedArticles.js
- added canonical urls to pages (using gatsby plugin)
- changed `href` of link elements, so that they point to correct url, i.e. `/career/`, not `/career`
=> MW-166-add-canonical

src/content/10-Fun-Retro-Tools-that-Will-Spice-Up-Your-Team-Meetings.md
Fixed URL of mentioned article, so that it doesn't point to 404.
=> MW-189 - Fix article link

src/components/Footer.js
Fixed order of links that appear in the footer.
=> MW-191 - fix footer link order
